var navs = [{
	"title": "人脸识别系统功能",
	"icon": "fa-cubes",
	"spread": true,
	"children": [{
		"title": "人脸数据库搜索",
		"icon": "&#xe641;",
		"href": "function1.html"
	}, {
		"title": "认证比对",
		"icon": "&#xe62e;",
		"href": "function2_121.html"
	}, {
		"title": "实时监控",
		"icon": "&#xe63c;",
		"href": "function3_rm.php"
	}, {
		"title": "视频倒查",
		"icon": "&#xe609;",
		"href": "function4_vr.php"
	}/*, {
		"title": "Tab选项卡",
		"icon": "&#xe62a;",
		"href": "tab.html"
	}, {
		"title": "辅助性元素",
		"icon": "&#xe60c;",
		"href": "auxiliar.html"
	}*/]
}/*, {
	"title": "组件",
	"icon": "fa-cogs",
	"spread": false,
	"children": [{
		"title": "Datatable",
		"icon": "fa-table",
		"href": "begtable.html"
	}, {
		"title": "Navbar组件",
		"icon": "fa-navicon",
		"href": "navbar.html"
	}, {
		"title": "Laytpl+Laypage",
		"icon": "&#xe628;",
		"href": "paging.html"
	}]
}, {
	"title": "第三方组件",
	"icon": "&#x1002;",
	"spread": false,
	"children": [{
		"title": "iCheck组件",
		"icon": "fa-check-square-o",
		"href": "icheck.html"
	}]
}, {
	"title": "地址本",
	"icon": "fa-address-book",
	"href": "",
	"spread": false,
	"children": [{
		"title": "Github",
		"icon": "fa-github",
		"href": "https://www.github.com/"
	}, {
		"title": "QQ",
		"icon": "fa-qq",
		"href": "http://www.qq.com/"
	}, {
		"title": "Fly社区",
		"icon": "&#xe609;",
		"href": "http://fly.layui.com/"
	}, {
		"title": "新浪微博",
		"icon": "fa-weibo",
		"href": "http://weibo.com/"
	}]
}, {
	"title": "这是一级导航",
	"icon": "fa-stop-circle",
	"href": "https://www.baidu.com",
	"spread": false
}*/];